# Generated by Django 5.2 on 2026-02-21 11:23

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DnsServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ip_address1', models.CharField(max_length=61)),
                ('ip_address2', models.CharField(max_length=61)),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('IPV4', 'ipv4'), ('IPV6', 'ipv6')], default='IPV4', max_length=10)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
