# Generated by Django 5.2 on 2026-02-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsserver',
            name='region',
            field=models.CharField(choices=[('eu', 'EU'), ('mea', 'MEA'), ('na', 'NA'), ('apac', 'APAC'), ('latam', 'LATAM')], default='na', max_length=5),
        ),
    ]
