# Generated by Django 5.2 on 2026-03-29 16:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usersettings'),
        ('dns_tools', '0003_add_initial_dns_servers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSHealthScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade', models.CharField(max_length=8)),
                ('checks', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=list)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_health_scans', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_health_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['user', '-scanned_at'], name='dns_tools_d_user_id_fb304a_idx'), models.Index(fields=['organization', '-scanned_at'], name='dns_tools_d_organiz_6ca869_idx'), models.Index(fields=['organization', 'domain_name'], name='dns_tools_d_organiz_535219_idx')],
            },
        ),
    ]
