# Generated by Django 5.2 on 2026-02-21 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_organization_license_expiry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_check_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_repositories', to='accounts.organization')),
            ],
            options={
                'ordering': ['-last_check_at'],
                'unique_together': {('owner', 'name', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='RepositoryCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.IntegerField(default=0)),
                ('level1_data', models.JSONField(blank=True, default=dict)),
                ('level2_data', models.JSONField(blank=True, default=dict)),
                ('level3_data', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('check_timestamp', models.DateTimeField(auto_now_add=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_checks', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='github_health_check.githubrepository')),
            ],
            options={
                'ordering': ['-check_timestamp'],
            },
        ),
    ]
