# Generated by Django 5.2 on 2026-03-29 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usersettings'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDnsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=16)),
                ('record_types', models.JSONField(default=list)),
                ('records', models.JSONField(default=dict)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_snapshots', to='assets.asset')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetDnsChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(max_length=32)),
                ('change_type', models.CharField(choices=[('added', 'Added'), ('removed', 'Removed'), ('modified', 'Modified'), ('status', 'Status')], max_length=16)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=16)),
                ('summary', models.CharField(max_length=255)),
                ('previous_value', models.JSONField(default=list)),
                ('current_value', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_change_events', to='assets.asset')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to='assets.assetdnssnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('dns_change', 'DNS change')], max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='assets.asset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_alerts', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='assets_asse_organiz_7bf3c1_idx'), models.Index(fields=['asset', '-created_at'], name='assets_asse_asset_i_936fb2_idx'), models.Index(fields=['is_read'], name='assets_asse_is_read_b349fb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='assetdnssnapshot',
            index=models.Index(fields=['asset', '-scanned_at'], name='assets_asse_asset_i_6f49df_idx'),
        ),
        migrations.AddIndex(
            model_name='assetdnssnapshot',
            index=models.Index(fields=['status'], name='assets_asse_status_ba66dd_idx'),
        ),
        migrations.AddIndex(
            model_name='assetdnschangeevent',
            index=models.Index(fields=['asset', '-created_at'], name='assets_asse_asset_i_86e48f_idx'),
        ),
        migrations.AddIndex(
            model_name='assetdnschangeevent',
            index=models.Index(fields=['severity'], name='assets_asse_severit_d32e6b_idx'),
        ),
    ]
