# Generated by Django 5.2 on 2026-04-05 18:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usersettings_notification_channels'),
        ('assets', '0002_assetdnssnapshot_assetdnschangeevent_assetalert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetalert',
            name='alert_type',
            field=models.CharField(choices=[('dns_change', 'DNS change'), ('website_content_change', 'Website content change'), ('github_secret_exposure', 'GitHub secret exposure')], max_length=32),
        ),
        migrations.CreateModel(
            name='AssetWebsiteSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=16)),
                ('response_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('page_title', models.CharField(blank=True, max_length=255)),
                ('content_length', models.PositiveIntegerField(default=0)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_snapshots', to='assets.asset')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetWebsiteChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('content', 'Content changed'), ('title', 'Page title changed'), ('status', 'Availability/status changed')], max_length=16)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('summary', models.CharField(max_length=255)),
                ('previous_value', models.JSONField(default=dict)),
                ('current_value', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_change_events', to='assets.asset')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to='assets.assetwebsitesnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetAutomatedScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('dns', 'DNS'), ('ip', 'IP reputation'), ('website', 'Website'), ('github', 'GitHub')], max_length=16)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='success', max_length=16)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automated_scan_runs', to='assets.asset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_automated_scan_runs', to='accounts.organization')),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['organization', '-scanned_at'], name='assets_asse_organiz_f5709d_idx'), models.Index(fields=['asset', '-scanned_at'], name='assets_asse_asset_i_8786d7_idx'), models.Index(fields=['scan_type', 'status'], name='assets_asse_scan_ty_5b201b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='assetwebsitesnapshot',
            index=models.Index(fields=['asset', '-scanned_at'], name='assets_asse_asset_i_22139a_idx'),
        ),
        migrations.AddIndex(
            model_name='assetwebsitesnapshot',
            index=models.Index(fields=['status'], name='assets_asse_status_ae1bcc_idx'),
        ),
        migrations.AddIndex(
            model_name='assetwebsitechangeevent',
            index=models.Index(fields=['asset', '-created_at'], name='assets_asse_asset_i_a77939_idx'),
        ),
        migrations.AddIndex(
            model_name='assetwebsitechangeevent',
            index=models.Index(fields=['severity'], name='assets_asse_severit_ca9b4f_idx'),
        ),
    ]
