# Generated by Django 5.2 on 2026-03-02 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainTyposquattingScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_domain', models.CharField(max_length=255)),
                ('similar_domains', models.JSONField(default=list)),
                ('threat_count', models.IntegerField(default=0)),
                ('total_variants', models.IntegerField(default=0)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typosquatting_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['user', '-scanned_at'], name='ip_tools_do_user_id_ed1e53_idx'), models.Index(fields=['original_domain'], name='ip_tools_do_origina_fb8726_idx')],
            },
        ),
        migrations.CreateModel(
            name='IPReputationScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('reputation_score', models.IntegerField()),
                ('risk_level', models.CharField(max_length=50)),
                ('is_proxy', models.BooleanField(default=False)),
                ('is_hosting', models.BooleanField(default=False)),
                ('is_mobile', models.BooleanField(default=False)),
                ('risk_factors', models.JSONField(default=list)),
                ('geolocation', models.JSONField(default=dict)),
                ('network', models.JSONField(default=dict)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_reputation_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['user', '-scanned_at'], name='ip_tools_ip_user_id_034134_idx'), models.Index(fields=['ip_address'], name='ip_tools_ip_ip_addr_877a26_idx')],
            },
        ),
    ]
