# Generated by Django 5.2 on 2026-03-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tools', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DomainTyposquattingScan',
        ),
    ]
