# Generated by Django 5.2 on 2026-04-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='incidentticket',
            new_name='incidents_i_organiz_b75826_idx',
            old_name='incidents_i_organiz_d8fbc3_idx',
        ),
        migrations.RenameIndex(
            model_name='incidentticket',
            new_name='incidents_i_organiz_608507_idx',
            old_name='incidents_i_organiz_3a1eb4_idx',
        ),
        migrations.RenameIndex(
            model_name='incidentticket',
            new_name='incidents_i_organiz_593ee4_idx',
            old_name='incidents_i_organiz_5837b0_idx',
        ),
        migrations.RenameIndex(
            model_name='incidentticket',
            new_name='incidents_i_organiz_d873fa_idx',
            old_name='incidents_i_organiz_4eb6f9_idx',
        ),
        migrations.RenameIndex(
            model_name='incidentticket',
            new_name='incidents_i_organiz_02c73c_idx',
            old_name='incidents_i_organiz_683494_idx',
        ),
        migrations.RenameIndex(
            model_name='incidentticket',
            new_name='incidents_i_organiz_30dff7_idx',
            old_name='incidents_i_organiz_11de2f_idx',
        ),
        migrations.RenameIndex(
            model_name='incidentticket',
            new_name='incidents_i_source_70cc61_idx',
            old_name='incidents_i_source_8803b6_idx',
        ),
    ]
