# Generated by Django 5.2 on 2026-04-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationevent',
            new_name='notificatio_organiz_bb836a_idx',
            old_name='notificatio_organiz_7fae7b_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationevent',
            new_name='notificatio_organiz_1a485f_idx',
            old_name='notificatio_organiz_34959b_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationevent',
            new_name='notificatio_test_ty_762d0d_idx',
            old_name='notificatio_test_ty_23609e_idx',
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='test_type',
            field=models.CharField(choices=[('dns_health', 'DNS health check'), ('dns_change', 'DNS change detection'), ('ip_reputation', 'IP reputation check'), ('website_content_change', 'Website content change detection'), ('github_health', 'GitHub health check'), ('github_secret_exposure', 'GitHub secret exposure detection')], max_length=32),
        ),
    ]
