# Generated by Django 6.0.2 on 2026-03-23 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_password_changed_at_loginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_token', models.TextField(blank=True, null=True)),
                ('use_cache', models.BooleanField(default=True)),
                ('cache_duration', models.IntegerField(default=60)),
                ('preferred_theme', models.CharField(choices=[('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple')], default='green', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]

