# Generated by Django 5.2 on 2026-04-19 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organization_notification_alert_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='notification_alert_threshold',
            field=models.PositiveSmallIntegerField(default=30, help_text='Notify when a test score is less than or equal to this threshold.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='teams_webhook_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
